import { supabase } from "../config/supabase";
import { applyStockMovement } from "./inventoryTransactionService";
import {
  downloadBulkImportReport,
  type BulkImportReportRow,
} from "../utils/bulkImportReport";

/* =========================================================================
 * Material Receipt - DRC Management (Sprint 1)
 *
 * Scope: create/list/update DRC header records only. No stock movement,
 * no inventory update, no inspection workflow - those are Sprint 2+.
 * ========================================================================= */

export type ReceiptMode = "Vehicle" | "Hand";

export type PackageType =
  | "Boxes"
  | "Bags"
  | "Bundles"
  | "Drums"
  | "Nos"
  | "Kg"
  | "MT"
  | "Others";

export const PACKAGE_TYPES: PackageType[] = [
  "Boxes",
  "Bags",
  "Bundles",
  "Drums",
  "Nos",
  "Kg",
  "MT",
  "Others",
];

export type ReceiptStatus = "Pending Inspection" | "Pending GRN" | "Closed";

export type InspectionStatus =
  | "Pending Inspection"
  | "Accepted"
  | "Rejected"
  | "Accepted with Remarks";

export interface PackageDetailRow {
  quantity: number;
  package_type: string;
  description: string;
}

export interface AttachmentFile {
  name: string;
  url: string;
  uploaded_at: string;
}

export interface ReceiptHeader {
  id: number;
  drc_number: string;
  receipt_mode: ReceiptMode;
  vehicle_number: string | null;
  /** @deprecated use package_details. Kept populated (derived) for
   * backward compatibility with anything still reading these columns. */
  package_count: number | null;
  /** @deprecated use package_details. */
  package_type: PackageType | string | null;
  package_details: PackageDetailRow[];
  vendor_name: string;
  /** @deprecated use sap_po_number / gem_order_number. Kept populated
   * (derived) for backward compatibility. */
  po_number: string | null;
  /** @deprecated use sap_po_date / gem_order_date. */
  po_date: string | null;
  sap_po_number: string | null;
  sap_po_date: string | null;
  gem_order_number: string | null;
  gem_order_date: string | null;
  invoice_number: string | null;
  invoice_date: string | null;
  challan_number: string | null;
  challan_date: string | null;
  eway_bill_number: string | null;
  eway_bill_date: string | null;
  lorry_receipt_number: string | null;
  lorry_receipt_date: string | null;
  weightment_slip_number: string | null;
  gross_weight: number | null;
  tare_weight: number | null;
  net_weight: number | null;
  remarks: string | null;
  photo_urls: string[];
  photo_paths: AttachmentFile[];
  attachment_paths: AttachmentFile[];
  status: ReceiptStatus;
  receipt_datetime: string;
  created_at: string;
  updated_at: string;
  // Sprint 2
  inspection_status: InspectionStatus | null;
  inspection_remarks: string | null;
  inspection_date: string | null;
  inspection_by: string | null;
  grn_number: string | null;
  grn_date: string | null;
  uploaded_by: string | null;
  upload_date: string | null;
  closed_date: string | null;
  closed_by: string | null;
}

/**
 * Fields the Create/Edit DRC form collects. drc_number, status, and
 * receipt_datetime are generated by the database (see the migration's
 * `generate_drc_number` trigger) and are never sent from the client on
 * create.
 */
export interface ReceiptFormInput {
  receipt_mode: ReceiptMode;
  vehicle_number: string;
  package_details: PackageDetailRow[];
  vendor_name: string;
  sap_po_number: string;
  sap_po_date: string;
  gem_order_number: string;
  gem_order_date: string;
  invoice_number: string;
  invoice_date: string;
  challan_number: string;
  challan_date: string;
  eway_bill_number: string;
  eway_bill_date: string;
  lorry_receipt_number: string;
  lorry_receipt_date: string;
  weightment_slip_number: string;
  gross_weight: string;
  tare_weight: string;
  net_weight: string;
  remarks: string;
}

const RECEIPT_PHOTOS_BUCKET = "receipt-photos";
const RECEIPT_FILES_BUCKET = "receipt-files";

const ALLOWED_DOCUMENT_EXTENSIONS = [
  "pdf",
  "doc",
  "docx",
  "xls",
  "xlsx",
  "jpg",
  "jpeg",
  "png",
];

function toNullable(value: string): string | null {
  const trimmed = value.trim();
  return trimmed ? trimmed : null;
}

function toNullableNumber(value: string): number | null {
  const trimmed = value.trim();
  if (!trimmed) return null;
  const parsed = Number(trimmed);
  return Number.isFinite(parsed) ? parsed : null;
}

/**
 * Cleans up a Package Details table: drops fully-empty rows, and coerces
 * quantity to a non-negative number.
 */
function cleanPackageDetails(rows: PackageDetailRow[]): PackageDetailRow[] {
  return rows
    .map((row) => ({
      quantity: Number.isFinite(row.quantity) ? Number(row.quantity) : 0,
      package_type: row.package_type.trim(),
      description: row.description.trim(),
    }))
    .filter(
      (row) => row.quantity > 0 || row.package_type || row.description
    );
}

function buildPayload(input: ReceiptFormInput) {
  const packageDetails = cleanPackageDetails(input.package_details);

  const sapPoNumber = toNullable(input.sap_po_number);
  const sapPoDate = toNullable(input.sap_po_date);
  const gemOrderNumber = toNullable(input.gem_order_number);
  const gemOrderDate = toNullable(input.gem_order_date);

  return {
    receipt_mode: input.receipt_mode,
    vehicle_number:
      input.receipt_mode === "Vehicle" ? toNullable(input.vehicle_number) : null,

    package_details: packageDetails,
    // Legacy columns, derived for backward compatibility with anything
    // still reading package_count / package_type directly.
    package_count:
      packageDetails.length > 0
        ? packageDetails.reduce((sum, r) => sum + r.quantity, 0)
        : null,
    package_type: packageDetails[0]?.package_type || null,

    vendor_name: input.vendor_name.trim(),

    sap_po_number: sapPoNumber,
    sap_po_date: sapPoDate,
    gem_order_number: gemOrderNumber,
    gem_order_date: gemOrderDate,
    // Legacy columns, derived so any existing search/report relying on
    // po_number / po_date still finds a value (SAP PO takes precedence).
    po_number: sapPoNumber ?? gemOrderNumber,
    po_date: sapPoDate ?? gemOrderDate,

    invoice_number: toNullable(input.invoice_number),
    invoice_date: toNullable(input.invoice_date),
    challan_number: toNullable(input.challan_number),
    challan_date: toNullable(input.challan_date),
    eway_bill_number: toNullable(input.eway_bill_number),
    eway_bill_date: toNullable(input.eway_bill_date),

    lorry_receipt_number: toNullable(input.lorry_receipt_number),
    lorry_receipt_date: toNullable(input.lorry_receipt_date),
    weightment_slip_number: toNullable(input.weightment_slip_number),
    gross_weight: toNullableNumber(input.gross_weight),
    tare_weight: toNullableNumber(input.tare_weight),
    net_weight: toNullableNumber(input.net_weight),

    remarks: toNullable(input.remarks),
  };
}

/**
 * Uploads photos to the `receipt-photos` Supabase Storage bucket and
 * returns their public URLs. A single failed upload is skipped (logged)
 * rather than blocking the rest, or the whole DRC save.
 */
export async function uploadReceiptPhotos(files: File[]): Promise<string[]> {
  const urls: string[] = [];

  for (const file of files) {
    const safeName = file.name.replace(/[^a-zA-Z0-9.\-_]/g, "_");
    const path = `${Date.now()}-${Math.random()
      .toString(36)
      .slice(2, 8)}-${safeName}`;

    const { error: uploadError } = await supabase.storage
      .from(RECEIPT_PHOTOS_BUCKET)
      .upload(path, file);

    if (uploadError) {
      console.error("Photo upload failed:", uploadError.message);
      continue;
    }

    const { data } = supabase.storage
      .from(RECEIPT_PHOTOS_BUCKET)
      .getPublicUrl(path);

    if (data?.publicUrl) {
      urls.push(data.publicUrl);
    }
  }

  return urls;
}

/**
 * Uploads supporting documents (invoice, challan, e-way bill, inspection
 * certificate, OEM/vendor documents, etc.) to the `receipt-files`
 * Supabase Storage bucket. Only allow-listed file types are uploaded;
 * anything else is skipped (logged) rather than blocking the rest.
 */
export async function uploadReceiptDocuments(
  files: File[]
): Promise<AttachmentFile[]> {
  const attachments: AttachmentFile[] = [];

  for (const file of files) {
    const extension = file.name.split(".").pop()?.toLowerCase() ?? "";

    if (!ALLOWED_DOCUMENT_EXTENSIONS.includes(extension)) {
      console.error(
        `Document upload skipped - unsupported file type: ${file.name}`
      );
      continue;
    }

    const safeName = file.name.replace(/[^a-zA-Z0-9.\-_]/g, "_");
    const path = `${Date.now()}-${Math.random()
      .toString(36)
      .slice(2, 8)}-${safeName}`;

    const { error: uploadError } = await supabase.storage
      .from(RECEIPT_FILES_BUCKET)
      .upload(path, file);

    if (uploadError) {
      console.error("Document upload failed:", uploadError.message);
      continue;
    }

    const { data } = supabase.storage
      .from(RECEIPT_FILES_BUCKET)
      .getPublicUrl(path);

    if (data?.publicUrl) {
      attachments.push({
        name: file.name,
        url: data.publicUrl,
        uploaded_at: new Date().toISOString(),
      });
    }
  }

  return attachments;
}

/**
 * Manual overrides for the auto-generated DRC No. / DRC Date, collected
 * from the Create DRC form when the operator switches on manual entry.
 * Both are optional; omit a key to keep the database-generated value.
 */
export interface DrcManualOverrides {
  drc_number?: string;
  receipt_datetime?: string;
}

/**
 * Best-effort suggestion for the next DRC No., used only to prefill the
 * manual-entry field in the Create DRC form (previous DRC No. + 1). It
 * increments the trailing numeric run of the most recently created DRC
 * No. (e.g. "DRC/26/000001" -> "DRC/26/000002"), preserving its
 * zero-padded width. Falls back to a fresh "DRC/{yy}/000001"-style
 * number if no DRC exists yet, or if the last one doesn't end in a
 * number.
 */
export async function getNextDrcNumberSuggestion(): Promise<string> {
  const currentYear = String(new Date().getFullYear()).slice(-2);
  const fallback = `DRC/${currentYear}/000001`;

  const { data, error } = await supabase
    .from("receipt_header")
    .select("drc_number")
    .order("id", { ascending: false })
    .limit(1)
    .maybeSingle();

  const lastDrcNumber = (data as { drc_number: string } | null)?.drc_number;

  if (error || !lastDrcNumber) {
    return fallback;
  }

  const match = lastDrcNumber.match(/^(.*?)(\d+)(\D*)$/);
  if (!match) {
    return fallback;
  }

  const [, prefix, digits, suffix] = match;
  const next = String(Number(digits) + 1).padStart(digits.length, "0");
  return `${prefix}${next}${suffix}`;
}

/**
 * Creates a new DRC. drc_number, status, and receipt_datetime are left
 * unset on the insert so the database trigger generates them - this
 * insert path is unchanged from before and always runs first.
 *
 * If `manualOverrides` is provided (operator switched on manual DRC No.
 * / Date entry), a follow-up update immediately applies the chosen
 * drc_number / receipt_datetime to the newly created row. Doing this as
 * a second update - rather than sending the overrides on the initial
 * insert - means the override never depends on how the database
 * trigger reacts to a pre-filled value: the trigger runs and fills its
 * defaults exactly as it always has, and the update then simply
 * replaces those columns like any other edit.
 */
export async function createReceipt(
  input: ReceiptFormInput,
  photoFiles: File[],
  documentFiles: File[] = [],
  manualOverrides?: DrcManualOverrides
): Promise<ReceiptHeader> {
  const photoUrls =
    photoFiles.length > 0 ? await uploadReceiptPhotos(photoFiles) : [];

  const photoPaths: AttachmentFile[] = photoUrls.map((url, index) => ({
    name: photoFiles[index]?.name ?? `photo-${index + 1}`,
    url,
    uploaded_at: new Date().toISOString(),
  }));

  const attachmentPaths =
    documentFiles.length > 0
      ? await uploadReceiptDocuments(documentFiles)
      : [];

  const payload = {
    ...buildPayload(input),
    photo_urls: photoUrls,
    photo_paths: photoPaths,
    attachment_paths: attachmentPaths,
  };

  const { data, error } = await supabase
    .from("receipt_header")
    .insert([payload])
    .select()
    .single();

  if (error) {
    console.error("========== SUPABASE ERROR ==========");
    console.error(error);
    console.error("Payload:");
    console.error(JSON.stringify(payload, null, 2));
    alert(
      error.message +
      "\n\nDetails: " + (error.details ?? "") +
      "\nHint: " + (error.hint ?? "")
    );
    throw error;
  }

  const created = data as ReceiptHeader;

  const overridePayload: Record<string, string> = {};
  if (manualOverrides?.drc_number) {
    overridePayload.drc_number = manualOverrides.drc_number;
  }
  if (manualOverrides?.receipt_datetime) {
    overridePayload.receipt_datetime = manualOverrides.receipt_datetime;
  }

  if (Object.keys(overridePayload).length === 0) {
    return created;
  }

  const { data: updated, error: updateError } = await supabase
    .from("receipt_header")
    .update(overridePayload)
    .eq("id", created.id)
    .select()
    .single();

  if (updateError) throw updateError;

  return updated as ReceiptHeader;
}

/**
 * Updates an existing DRC's details. Sprint 1 only edits header fields -
 * drc_number and status are never changed here.
 */
export async function updateReceipt(
  id: number,
  input: ReceiptFormInput,
  newPhotoFiles: File[],
  keptPhotoUrls: string[],
  newDocumentFiles: File[] = [],
  keptAttachments: AttachmentFile[] = []
): Promise<ReceiptHeader> {
  const uploadedUrls =
    newPhotoFiles.length > 0 ? await uploadReceiptPhotos(newPhotoFiles) : [];

  const newPhotoPaths: AttachmentFile[] = uploadedUrls.map((url, index) => ({
    name: newPhotoFiles[index]?.name ?? `photo-${index + 1}`,
    url,
    uploaded_at: new Date().toISOString(),
  }));

  const newAttachments =
    newDocumentFiles.length > 0
      ? await uploadReceiptDocuments(newDocumentFiles)
      : [];

  const photoUrls = [...keptPhotoUrls, ...uploadedUrls];

  const payload = {
    ...buildPayload(input),
    photo_urls: photoUrls,
    photo_paths: photoUrls.map(
      (url) =>
        newPhotoPaths.find((p) => p.url === url) ?? {
          name: url.split("/").pop() ?? url,
          url,
          uploaded_at: new Date().toISOString(),
        }
    ),
    attachment_paths: [...keptAttachments, ...newAttachments],
  };

  const { data, error } = await supabase
    .from("receipt_header")
    .update(payload)
    .eq("id", id)
    .select()
    .single();

  if (error) {
    console.error("========== SUPABASE ERROR ==========");
    console.error(error);
    console.error("Payload:");
    console.error(JSON.stringify(payload, null, 2));
    alert(
      error.message +
      "\n\nDetails: " + (error.details ?? "") +
      "\nHint: " + (error.hint ?? "")
    );
    throw error;
  }

  return data as ReceiptHeader;
}

export interface ReceiptFilters {
  search?: string;
  fromDate?: string;
  toDate?: string;
}

/**
 * Fetches DRCs, newest first. `search` matches DRC Number, Vendor,
 * SAP PO Number, Invoice Number, or Vehicle Number. `fromDate`/`toDate`
 * filter by Receipt Date (yyyy-mm-dd).
 */
export async function getReceipts(
  filters: ReceiptFilters = {}
): Promise<ReceiptHeader[]> {
  let query = supabase
    .from("receipt_header")
    .select("*")
    .order("receipt_datetime", { ascending: false });

  const search = filters.search?.trim();

  if (search) {
    const safe = search.replace(/[%_]/g, (match) => `\\${match}`);
    query = query.or(
      `drc_number.ilike.%${safe}%,vendor_name.ilike.%${safe}%,po_number.ilike.%${safe}%,sap_po_number.ilike.%${safe}%,gem_order_number.ilike.%${safe}%,invoice_number.ilike.%${safe}%,vehicle_number.ilike.%${safe}%`
    );
  }

  if (filters.fromDate) {
    query = query.gte("receipt_datetime", `${filters.fromDate}T00:00:00`);
  }

  if (filters.toDate) {
    query = query.lte("receipt_datetime", `${filters.toDate}T23:59:59`);
  }

  const { data, error } = await query;

  if (error) {
    console.error(error);
    return [];
  }

  return (data ?? []) as ReceiptHeader[];
}

export async function getReceiptById(
  id: number
): Promise<ReceiptHeader | null> {
  const { data, error } = await supabase
    .from("receipt_header")
    .select("*")
    .eq("id", id)
    .maybeSingle();

  if (error) {
    console.error(error);
    return null;
  }

  return data as ReceiptHeader | null;
}

export interface ReceiptSummary {
  pendingInspection: number;
  pendingGrn: number;
  closed: number;
  total: number;
}

/**
 * Counts DRCs by status for the four summary cards on the Receipt
 * Register.
 */
export async function getReceiptSummary(): Promise<ReceiptSummary> {
  const { data, error } = await supabase.from("receipt_header").select("status");

  if (error) {
    console.error(error);
    return { pendingInspection: 0, pendingGrn: 0, closed: 0, total: 0 };
  }

  const rows = (data ?? []) as { status: ReceiptStatus }[];

  return {
    pendingInspection: rows.filter((r) => r.status === "Pending Inspection")
      .length,
    pendingGrn: rows.filter((r) => r.status === "Pending GRN").length,
    closed: rows.filter((r) => r.status === "Closed").length,
    total: rows.length,
  };
}

/* =========================================================================
 * Sprint 2: Inspection
 * ========================================================================= */

export interface InspectionHistoryEntry {
  id: number;
  receipt_id: number;
  inspection_status: InspectionStatus;
  inspection_remarks: string | null;
  inspection_by: string | null;
  inspection_date: string;
}

/**
 * Records an inspection action for a DRC: appends an entry to
 * `receipt_inspection_history` and updates the DRC's current inspection
 * fields. If the outcome is Accepted or Accepted with Remarks, the DRC's
 * overall status automatically moves to "Pending GRN" - otherwise the
 * DRC's overall status is left as-is (e.g. a Rejected inspection allows
 * the DRC to be re-inspected later without changing its status).
 */
export async function submitInspection(
  receiptId: number,
  inspectionStatus: InspectionStatus,
  inspectionRemarks: string,
  inspectionBy: string
): Promise<ReceiptHeader> {
  const nowIso = new Date().toISOString();
  const remarks = inspectionRemarks.trim() || null;
  const by = inspectionBy.trim() || null;

  const { error: historyError } = await supabase
    .from("receipt_inspection_history")
    .insert([
      {
        receipt_id: receiptId,
        inspection_status: inspectionStatus,
        inspection_remarks: remarks,
        inspection_by: by,
        inspection_date: nowIso,
      },
    ]);

  if (historyError) throw historyError;

  const headerUpdate: Record<string, unknown> = {
    inspection_status: inspectionStatus,
    inspection_remarks: remarks,
    inspection_by: by,
    inspection_date: nowIso,
  };

  if (
    inspectionStatus === "Accepted" ||
    inspectionStatus === "Accepted with Remarks"
  ) {
    headerUpdate.status = "Pending GRN";
  }

  const { data, error } = await supabase
    .from("receipt_header")
    .update(headerUpdate)
    .eq("id", receiptId)
    .select()
    .single();

  if (error) throw error;

  return data as ReceiptHeader;
}

export async function getInspectionHistory(
  receiptId: number
): Promise<InspectionHistoryEntry[]> {
  const { data, error } = await supabase
    .from("receipt_inspection_history")
    .select("*")
    .eq("receipt_id", receiptId)
    .order("inspection_date", { ascending: false });

  if (error) {
    console.error(error);
    return [];
  }

  return (data ?? []) as InspectionHistoryEntry[];
}

/* =========================================================================
 * Sprint 2: GRN Upload
 * ========================================================================= */

/** The sentinel location used for GRN-received stock (no put-away location
 * is captured on the GRN Excel - Material Code + Quantity only). */
export const GRN_UNALLOCATED_LOCATION = "UNALLOCATED";

export interface GrnImportRow {
  rowNumber: number;
  material_code: string;
  quantity: number;
}

export interface GrnFormatInvalidRow {
  rowNumber: number;
  material_code: string;
  quantityRaw: string;
  errors: string[];
}

export interface GrnParseResult {
  totalRecords: number;
  /** Valid rows, already de-duplicated by Material Code (quantities summed). */
  mergedRows: GrnImportRow[];
  /** Rows rejected for format reasons (missing code, bad quantity) before
   * any database lookup happens. */
  invalidRows: GrnFormatInvalidRow[];
  /** How many raw rows collapsed into each merged row (for information only). */
  duplicateCodeCount: number;
}

function getGrnFieldValue(
  row: Record<string, unknown>,
  aliases: string[]
): string {
  const keys = Object.keys(row);

  for (const alias of aliases) {
    const match = keys.find(
      (key) => key.trim().toLowerCase() === alias.toLowerCase()
    );

    if (match !== undefined) {
      const value = row[match];
      return value === null || value === undefined
        ? ""
        : String(value).trim();
    }
  }

  return "";
}

function isGrnRowBlank(row: Record<string, unknown>): boolean {
  return Object.values(row).every((value) => {
    if (value === null || value === undefined) return true;
    return String(value).trim() === "";
  });
}

function parseGrnQuantity(raw: string): number {
  const cleaned = raw.replace(/,/g, "").trim();
  if (!cleaned) return NaN;
  return Number(cleaned);
}

/**
 * Parses a GRN Excel file (columns: Material Code, Quantity). This is a
 * pure, in-memory step - no database calls - so it stays fast even for
 * 10,000+ rows. Duplicate Material Codes are summed into a single row
 * here rather than being treated as an error.
 */
export function parseGrnExcelRows(
  rawRows: Record<string, unknown>[]
): GrnParseResult {
  const invalidRows: GrnFormatInvalidRow[] = [];
  const merged = new Map<string, { rowNumber: number; quantity: number }>();

  let totalRecords = 0;
  let rawValidRowCount = 0;

  rawRows.forEach((row, index) => {
    if (isGrnRowBlank(row)) {
      return;
    }

    totalRecords += 1;

    const rowNumber = index + 2;

    const materialCode = getGrnFieldValue(row, [
      "Material Code",
      "material_code",
      "Material",
    ]);

    const quantityRaw = getGrnFieldValue(row, [
      "Quantity",
      "Qty",
      "GRN Quantity",
    ]);

    const errors: string[] = [];

    if (!materialCode) {
      errors.push("Material Code is required.");
    }

    const quantity = parseGrnQuantity(quantityRaw);

    if (!quantityRaw) {
      errors.push("Quantity is required.");
    } else if (Number.isNaN(quantity)) {
      errors.push("Quantity must be a number.");
    } else if (quantity <= 0) {
      errors.push("Quantity must be greater than zero.");
    }

    if (errors.length > 0) {
      invalidRows.push({
        rowNumber,
        material_code: materialCode,
        quantityRaw,
        errors,
      });
      return;
    }

    rawValidRowCount += 1;

    const key = materialCode.toUpperCase();
    const existing = merged.get(key);

    if (existing) {
      existing.quantity += quantity;
    } else {
      merged.set(key, { rowNumber, quantity });
    }
  });

  const mergedRows: GrnImportRow[] = Array.from(merged.entries()).map(
    ([materialCode, v]) => ({
      rowNumber: v.rowNumber,
      material_code: materialCode,
      quantity: v.quantity,
    })
  );

  return {
    totalRecords,
    mergedRows,
    invalidRows,
    duplicateCodeCount: rawValidRowCount - mergedRows.length,
  };
}

export interface GrnMaterialValidationResult {
  /** Rows whose Material Code exists in material_master. */
  knownRows: GrnImportRow[];
  /** Material Codes that do not exist in material_master. */
  unknownMaterials: GrnImportRow[];
}

/**
 * Checks Material Code existence against material_master in a single
 * batched query (`.in()`), regardless of how many rows were uploaded -
 * this is what keeps validation fast for 10,000+ row files.
 */
export async function validateGrnMaterials(
  rows: GrnImportRow[]
): Promise<GrnMaterialValidationResult> {
  if (rows.length === 0) {
    return { knownRows: [], unknownMaterials: [] };
  }

  const codes = rows.map((r) => r.material_code);

  const { data, error } = await supabase
    .from("material_master")
    .select("material_code")
    .in("material_code", codes);

  if (error) {
    console.error(error);
    return { knownRows: [], unknownMaterials: rows };
  }

  const knownSet = new Set(
    (data ?? []).map((m: { material_code: string }) => m.material_code)
  );

  const knownRows: GrnImportRow[] = [];
  const unknownMaterials: GrnImportRow[] = [];

  rows.forEach((row) => {
    if (knownSet.has(row.material_code)) {
      knownRows.push(row);
    } else {
      unknownMaterials.push(row);
    }
  });

  return { knownRows, unknownMaterials };
}

export interface GrnImportFailure {
  material_code: string;
  quantity: number;
  rowNumber: number;
  error: string;
}

export interface GrnImportSuccess {
  material_code: string;
  quantity: number;
  rowNumber: number;
}

export interface GrnImportSummary {
  receiptId: number;
  grnId: number | null;
  grnNumber: string;
  imported: number;
  failed: number;
  totalQuantity: number;
  successes: GrnImportSuccess[];
  failures: GrnImportFailure[];
  closed: boolean;
  receipt: ReceiptHeader | null;
}

/**
 * Imports a validated, de-duplicated set of GRN rows for a DRC:
 *
 * 1. Batch-fetches any existing UNALLOCATED material_allocation rows for
 *    these materials in one query (no duplicate allocations are ever
 *    created - an existing row's quantity is increased instead).
 * 2. For every material, calls the Inventory Transaction Engine's
 *    `applyStockMovement` (transactionType "MATERIAL_RECEIPT") to
 *    increase stock. One failing material never blocks the rest.
 * 3. Bulk-inserts all GRN line items in a single insert call.
 * 4. Creates the `receipt_grn` header row and, if at least one material
 *    was imported successfully, closes the DRC (status, GRN details,
 *    closed date/by) in one update call.
 */
export async function importGrn(
  receiptId: number,
  grnNumber: string,
  grnDate: string,
  uploadedBy: string,
  rows: GrnImportRow[]
): Promise<GrnImportSummary> {
  const summary: GrnImportSummary = {
    receiptId,
    grnId: null,
    grnNumber,
    imported: 0,
    failed: 0,
    totalQuantity: 0,
    successes: [],
    failures: [],
    closed: false,
    receipt: null,
  };

  if (rows.length === 0) {
    return summary;
  }

  const codes = rows.map((r) => r.material_code);

  const { data: existingAllocations, error: fetchError } = await supabase
    .from("material_allocation")
    .select("id, material_code, quantity")
    .eq("location_code", GRN_UNALLOCATED_LOCATION)
    .in("material_code", codes);

  if (fetchError) {
    console.error(fetchError);
  }

  const allocationMap = new Map<
    string,
    { id: number; quantity: number }
  >(
    (existingAllocations ?? []).map(
      (a: { id: number; material_code: string; quantity: number }) => [
        a.material_code,
        { id: a.id, quantity: Number(a.quantity) },
      ]
    )
  );

  const importedLines: { material_code: string; quantity: number }[] = [];

  for (const row of rows) {
    try {
      const existing = allocationMap.get(row.material_code);
      const prevQuantity = existing ? existing.quantity : 0;
      const newQuantity = prevQuantity + row.quantity;

      await applyStockMovement({
        materialCode: row.material_code,
        locationCode: GRN_UNALLOCATED_LOCATION,
        prevQuantity,
        newQuantity,
        allocationId: existing?.id,
        transactionType: "MATERIAL_RECEIPT",
        referenceType: "GRN",
        referenceNumber: grnNumber,
        reason: "GRN Receipt",
      });

      // Keep the running balance current in case the same material
      // appears again (already de-duplicated upstream, but this keeps
      // the map correct defensively).
      allocationMap.set(row.material_code, {
        id: existing?.id ?? -1,
        quantity: newQuantity,
      });

      importedLines.push({
        material_code: row.material_code,
        quantity: row.quantity,
      });

      summary.imported += 1;
      summary.totalQuantity += row.quantity;
      summary.successes.push({
        material_code: row.material_code,
        quantity: row.quantity,
        rowNumber: row.rowNumber,
      });
    } catch (err) {
      summary.failed += 1;
      summary.failures.push({
        material_code: row.material_code,
        quantity: row.quantity,
        rowNumber: row.rowNumber,
        error: err instanceof Error ? err.message : "Unknown error.",
      });
    }
  }

  if (summary.imported === 0) {
    return summary;
  }

  const { data: grnHeader, error: grnError } = await supabase
    .from("receipt_grn")
    .insert([
      {
        receipt_id: receiptId,
        grn_number: grnNumber,
        grn_date: grnDate,
        uploaded_by: uploadedBy.trim() || null,
        material_count: summary.imported,
        total_quantity: summary.totalQuantity,
      },
    ])
    .select()
    .single();

  if (grnError) {
    console.error(grnError);
  } else {
    summary.grnId = grnHeader.id;

    // Bulk insert every line item in a single call.
    const { error: linesError } = await supabase
      .from("receipt_grn_lines")
      .insert(
        importedLines.map((line) => ({
          grn_id: grnHeader.id,
          material_code: line.material_code,
          quantity: line.quantity,
        }))
      );

    if (linesError) {
      console.error(linesError);
    }
  }

  const nowIso = new Date().toISOString();

  const { data: updatedReceipt, error: closeError } = await supabase
    .from("receipt_header")
    .update({
      grn_number: grnNumber,
      grn_date: grnDate,
      uploaded_by: uploadedBy.trim() || null,
      upload_date: nowIso,
      status: "Closed",
      closed_date: nowIso,
      closed_by: uploadedBy.trim() || null,
    })
    .eq("id", receiptId)
    .select()
    .single();

  if (closeError) {
    console.error(closeError);
  } else {
    summary.closed = true;
    summary.receipt = updatedReceipt as ReceiptHeader;
  }

  return summary;
}

const GRN_REPORT_COLUMNS = [
  { header: "Material Code", key: "material_code" },
  { header: "Quantity", key: "quantity" },
];

/**
 * Builds and immediately downloads a combined Excel report for a GRN bulk
 * import, covering every row submitted: rows rejected for format reasons
 * (missing code, bad quantity), rows rejected because the Material Code is
 * unknown, rows imported successfully, and rows that failed while being
 * applied - along with the reason for anything other than a clean success.
 */
export function downloadGrnImportReport(
  totalRecords: number,
  formatInvalidRows: GrnFormatInvalidRow[],
  unknownMaterials: GrnImportRow[],
  summary: GrnImportSummary
): void {
  const formatRejected: BulkImportReportRow[] = formatInvalidRows.map((row) => ({
    rowNumber: row.rowNumber,
    status: "Rejected",
    reason: row.errors.join("; "),
    data: {
      material_code: row.material_code,
      quantity: row.quantityRaw,
    },
  }));

  const unknownRejected: BulkImportReportRow[] = unknownMaterials.map((row) => ({
    rowNumber: row.rowNumber,
    status: "Rejected",
    reason: `Material Code "${row.material_code}" was not found.`,
    data: {
      material_code: row.material_code,
      quantity: row.quantity,
    },
  }));

  const succeeded: BulkImportReportRow[] = summary.successes.map((row) => ({
    rowNumber: row.rowNumber,
    status: "Imported",
    data: {
      material_code: row.material_code,
      quantity: row.quantity,
    },
  }));

  const failed: BulkImportReportRow[] = summary.failures.map((row) => ({
    rowNumber: row.rowNumber,
    status: "Failed",
    reason: row.error,
    data: {
      material_code: row.material_code,
      quantity: row.quantity,
    },
  }));

  const safeGrnNumber =
    summary.grnNumber.replace(/[^a-zA-Z0-9_-]/g, "_") || "Import";

  downloadBulkImportReport({
    fileNamePrefix: `GRN_${safeGrnNumber}`,
    columns: GRN_REPORT_COLUMNS,
    rows: [...formatRejected, ...unknownRejected, ...succeeded, ...failed],
    summary: [
      { label: "Total Excel Rows", value: totalRecords },
      { label: "Format Rejected", value: formatInvalidRows.length },
      { label: "Unknown Material Rejected", value: unknownMaterials.length },
      { label: "Imported", value: summary.imported },
      { label: "Failed", value: summary.failed },
      { label: "Total Quantity", value: summary.totalQuantity },
    ],
  });
}

export interface GrnHistoryEntry {
  id: number;
  receipt_id: number;
  grn_number: string;
  grn_date: string;
  uploaded_by: string | null;
  upload_date: string;
  material_count: number;
  total_quantity: number;
}

export async function getGrnHistory(
  receiptId: number
): Promise<GrnHistoryEntry[]> {
  const { data, error } = await supabase
    .from("receipt_grn")
    .select("*")
    .eq("receipt_id", receiptId)
    .order("upload_date", { ascending: false });

  if (error) {
    console.error(error);
    return [];
  }

  return (data ?? []) as GrnHistoryEntry[];
}

export interface GrnLine {
  id: number;
  grn_id: number;
  material_code: string;
  quantity: number;
}

export async function getGrnLines(grnId: number): Promise<GrnLine[]> {
  const { data, error } = await supabase
    .from("receipt_grn_lines")
    .select("*")
    .eq("grn_id", grnId)
    .order("material_code");

  if (error) {
    console.error(error);
    return [];
  }

  return (data ?? []) as GrnLine[];
}

/**
 * Generates the downloadable GRN Excel template (Material Code, Quantity)
 * with a couple of sample rows, via SheetJS. Called from the UI layer,
 * which triggers the actual file download.
 */
export function buildGrnTemplateRows(): { headers: string[]; rows: (string | number)[][] } {
  return {
    headers: ["Material Code", "Quantity"],
    rows: [
      ["9000000001", 10],
      ["9000000002", 25],
    ],
  };
}

/* =========================================================================
 * Sprint 3: Email Templates (HTML generation only - no SMTP, no sending)
 * ========================================================================= */

function formatMailDate(value: string | null): string {
  if (!value) return "-";
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return value;
  return d.toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

/**
 * Builds the HTML body for an "inspection required" email addressed to
 * the user department responsible for inspecting a DRC. Returns an HTML
 * string only - this function never sends anything.
 */
export function generateInspectionMail(receipt: ReceiptHeader): string {
  return `
    <div style="font-family: Arial, sans-serif; color: #1a1a1a; line-height: 1.6;">
      <h2 style="margin-bottom: 4px;">Inspection Required</h2>
      <table style="border-collapse: collapse; margin: 12px 0;">
        <tr><td style="padding: 4px 12px 4px 0; font-weight: 600;">DRC Number</td><td style="padding: 4px 0;">${receipt.drc_number}</td></tr>
        <tr><td style="padding: 4px 12px 4px 0; font-weight: 600;">Supplier Name</td><td style="padding: 4px 0;">${receipt.vendor_name}</td></tr>
        <tr><td style="padding: 4px 12px 4px 0; font-weight: 600;">Receipt Date</td><td style="padding: 4px 0;">${formatMailDate(receipt.receipt_datetime)}</td></tr>
        <tr><td style="padding: 4px 12px 4px 0; font-weight: 600;">SAP PO Number</td><td style="padding: 4px 0;">${receipt.sap_po_number ?? "-"}</td></tr>
        <tr><td style="padding: 4px 12px 4px 0; font-weight: 600;">GeM Order Number</td><td style="padding: 4px 0;">${receipt.gem_order_number ?? "-"}</td></tr>
      </table>
      <p>Please complete inspection within 7 days.</p>
    </div>
  `.trim();
}

/**
 * Builds the HTML body for a "resolve this issue" email addressed to a
 * supplier, based on an inspection outcome. Returns an HTML string only -
 * this function never sends anything.
 */
export function generateSupplierIssueMail(
  receipt: ReceiptHeader,
  issueType: string
): string {
  return `
    <div style="font-family: Arial, sans-serif; color: #1a1a1a; line-height: 1.6;">
      <h2 style="margin-bottom: 4px;">Material Receipt Issue</h2>
      <table style="border-collapse: collapse; margin: 12px 0;">
        <tr><td style="padding: 4px 12px 4px 0; font-weight: 600;">DRC Number</td><td style="padding: 4px 0;">${receipt.drc_number}</td></tr>
        <tr><td style="padding: 4px 12px 4px 0; font-weight: 600;">Supplier Name</td><td style="padding: 4px 0;">${receipt.vendor_name}</td></tr>
        <tr><td style="padding: 4px 12px 4px 0; font-weight: 600;">Issue Type</td><td style="padding: 4px 0;">${issueType}</td></tr>
        <tr><td style="padding: 4px 12px 4px 0; font-weight: 600;">Inspection Remarks</td><td style="padding: 4px 0;">${receipt.inspection_remarks ?? "-"}</td></tr>
      </table>
      <p>Please resolve the above issue at the earliest.</p>
    </div>
  `.trim();
}
