import { Paper, Typography, Grid, Divider, Box, LinearProgress } from "@mui/material";
import type { Material } from "../types/material";

interface Props {
  material: Material | null;
    allocatedQty: number;
    }

    export default function AllocationSummary({
      material,
        allocatedQty,
        }: Props) {
          if (!material) {
              return (
                    <Paper elevation={3} sx={{ p: 2, mb: 2, borderRadius: 2 }}>
                            <Typography variant="subtitle1" fontWeight="bold">
                                      Material Information
                                              </Typography>

                                                      <Typography variant="body2" color="text.secondary" sx={{ mt: 1 }}>
                                                                Please select a material.
                                                                        </Typography>
                                                                              </Paper>
                                                                                  );
                                                                                    }

                                                                                      const stock = material.current_quantity;
                                                                                        const balance = stock - allocatedQty;

                                                                                          const allocatedPercent =
                                                                                              stock > 0 ? Math.min((allocatedQty / stock) * 100, 100) : 0;

                                                                                                const balancePercent = stock > 0 ? (balance / stock) * 100 : 0;

                                                                                                  let balanceColor = "success.main";
                                                                                                    let progressColor: "success" | "warning" | "error" = "success";

                                                                                                      if (balance <= 0) {
                                                                                                          balanceColor = "error.main";
                                                                                                              progressColor = "error";
                                                                                                                } else if (balancePercent <= 20) {
                                                                                                                    balanceColor = "warning.main";
                                                                                                                        progressColor = "warning";
                                                                                                                          }

                                                                                                                            return (
                                                                                                                                <Paper elevation={3} sx={{ p: 2, mb: 2, borderRadius: 2 }}>
                                                                                                                                      <Box
                                                                                                                                              sx={{
                                                                                                                                                        display: "flex",
                                                                                                                                                                  justifyContent: "space-between",
                                                                                                                                                                            alignItems: "flex-start",
                                                                                                                                                                                      gap: 1,
                                                                                                                                                                                                flexWrap: "wrap",
                                                                                                                                                                                                        }}
                                                                                                                                                                                                              >
                                                                                                                                                                                                                      <Box sx={{ minWidth: 0 }}>
                                                                                                                                                                                                                                <Typography variant="subtitle1" fontWeight="bold" noWrap>
                                                                                                                                                                                                                                            {material.material_code}
                                                                                                                                                                                                                                                      </Typography>

                                                                                                                                                                                                                                                                <Typography
                                                                                                                                                                                                                                                                            variant="body2"
                                                                                                                                                                                                                                                                                        color="text.secondary"
                                                                                                                                                                                                                                                                                                    sx={{ overflowWrap: "break-word" }}
                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                          {material.short_description}
                                                                                                                                                                                                                                                                                                                                    </Typography>
                                                                                                                                                                                                                                                                                                                                            </Box>

                                                                                                                                                                                                                                                                                                                                                    <Typography
                                                                                                                                                                                                                                                                                                                                                              variant="caption"
                                                                                                                                                                                                                                                                                                                                                                        color="text.secondary"
                                                                                                                                                                                                                                                                                                                                                                                  sx={{ whiteSpace: "nowrap" }}
                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                    UoM: {material.uom}
                                                                                                                                                                                                                                                                                                                                                                                                            </Typography>
                                                                                                                                                                                                                                                                                                                                                                                                                  </Box>

                                                                                                                                                                                                                                                                                                                                                                                                                        <Divider sx={{ my: 1.5 }} />

                                                                                                                                                                                                                                                                                                                                                                                                                              <Grid container spacing={1}>
                                                                                                                                                                                                                                                                                                                                                                                                                                      <Grid size={4}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <Typography
                                                                                                                                                                                                                                                                                                                                                                                                                                                            variant="caption"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color="text.secondary"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    display="block"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Stock
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Typography>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Typography variant="subtitle2" fontWeight="bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {stock}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Typography>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Grid>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Grid size={4}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Typography
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          variant="caption"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color="text.secondary"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  display="block"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Allocated
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Typography>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Typography
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        variant="subtitle2"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontWeight="bold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color="primary.main"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {allocatedQty}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Typography>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Grid>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Grid size={4}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Typography
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      variant="caption"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  color="text.secondary"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              display="block"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Balance
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Typography>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Typography
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    variant="subtitle2"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontWeight="bold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            sx={{ color: balanceColor }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {balance}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Typography>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Grid>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Grid>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Box sx={{ mt: 2 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Box
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  sx={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              display: "flex",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          justifyContent: "space-between",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      mb: 0.5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Typography variant="caption" color="text.secondary">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Allocated {allocatedQty} / {stock}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Typography>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Typography variant="caption" color="text.secondary">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {allocatedPercent.toFixed(0)}%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Typography>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Box>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <LinearProgress
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  variant="determinate"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={allocatedPercent}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color={progressColor}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sx={{ height: 8, borderRadius: 4 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Box>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Paper>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    