-- Stores a full, row-level result report for every bulk Excel import that
-- runs anywhere in the app (Material Master, Location Master, Bulk
-- Allocate, Opening Stock, GRN receipt import). Backs the Reports >
-- Import Reports tab, so a bulk import's outcome survives navigating away
-- or reloading and can be re-downloaded as the original Excel report at
-- any time.
--
-- No RLS policy is added here, matching every other table in this schema
-- (e.g. material_master, location_master) which the app reads/writes
-- directly with the Supabase anon key and no auth layer.
create table if not exists public.bulk_import_history (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  import_type text not null,
  file_name text,
  total_rows integer not null default 0,
  success_count integer not null default 0,
  rejected_count integer not null default 0,
  failed_count integer not null default 0,
  report_columns jsonb not null,
  report_rows jsonb not null,
  report_summary jsonb not null
);

create index if not exists bulk_import_history_created_at_idx
  on public.bulk_import_history (created_at desc);
