-- Logs every DRC-related notification email sent from the Material
-- Receipt (DRC) module: the "Inspection Required" mail sent to the user
-- department when a DRC is created, and the "Shortage" / "Discrepancy"
-- mails sent to the supplier when an inspection finds a shortfall or a
-- mismatch in the supplied material. Backs the "Mail History" section on
-- the DRC view, and is written to whether or not the send actually
-- succeeded (status/error_message capture the outcome) so a failed send
-- is never silently lost.
--
-- No RLS policy is added here, matching every other table in this schema
-- (e.g. bulk_import_history, material_master) which the app reads/writes
-- directly with the Supabase anon key and no auth layer.
create table if not exists public.receipt_mail_log (
  id bigint generated by default as identity primary key,
  receipt_id bigint not null references public.receipt_header (id) on delete cascade,
  mail_type text not null,
  recipient_email text not null,
  subject text not null,
  status text not null default 'Sent',
  error_message text,
  sent_by text,
  sent_at timestamptz not null default now()
);

create index if not exists receipt_mail_log_receipt_id_idx
  on public.receipt_mail_log (receipt_id);

create index if not exists receipt_mail_log_sent_at_idx
  on public.receipt_mail_log (sent_at desc);
