-- Live reconciliation table for the periodic "Stock Update (Bulk)" import:
-- one row per material whose latest uploaded physical-stock count differs
-- from the system's current total (sum of material_allocation rows). This
-- is NOT an append-only log like inventory_transactions - a later upload
-- for the same material overwrites its row (upsert on material_code), and
-- the row is deleted once a user resolves it (either by applying the
-- one-click fix or by completing a manual reconciliation).
--
-- No RLS policy is added here, matching every other table in this schema
-- (e.g. material_master, material_allocation) which the app reads/writes
-- directly with the Supabase anon key and no auth layer.
create table if not exists public.pending_stock_updates (
  id bigint generated by default as identity primary key,
  material_code text not null unique,
  short_description text,
  uom text,
  uploaded_qty numeric not null,
  system_qty_at_upload numeric not null,
  difference numeric not null,
  batch_file_name text,
  uploaded_at timestamptz not null default now()
);

create index if not exists pending_stock_updates_material_code_idx
  on public.pending_stock_updates (material_code);
