-- SAP Material History (MB51) + Current Stock (MB52) import support.
--
-- The user exports two sheets from SAP and imports them from
-- Inventory > Stock Update:
--
--   MB51 - Material Document List ("material history"): one row per
--          movement with signed quantity, storage location, movement
--          type, posting date, material document, PO, vendor, invoice
--          and user. Stored as an immutable mirror in
--          sap_material_documents - it is history only and never
--          affects app stock.
--
--   MB52 - Current Stock Overview: one row per material + storage
--          location with the current quantity. This is a point-in-time
--          snapshot; it replaces sap_stock_distribution and drives the
--          reconciliation reviews against the app's physical stock.
--
-- Design rules agreed with the owner:
--   1. SAP storage locations (AFCN / REVN / ESRN ...) are accounting
--      buckets per material, NOT physical bins - they never go into
--      location_master and never into material_allocation.
--   2. The app's physical ledger (inventory_transactions) stays
--      app-only. SAP history lives in its own table.
--   3. Reconciliation is at material-total level only: SAP total vs
--      app total. Differences become stock_reconciliation_reviews for
--      a person to apply (as one audited ADJUSTMENT) or dismiss.
--   4. Imports never write to material_allocation, inventory_transactions
--      or location_master.
--
-- All statements are guarded so this is safe to run any number of
-- times against an existing database. RLS mirrors the tenant_isolation
-- pattern from 0005.

begin;

-- ---------------------------------------------------------------------------
-- 1. sap_material_documents - MB51 history (one row per movement)
-- ---------------------------------------------------------------------------
create table if not exists public.sap_material_documents (
  id bigint generated by default as identity primary key,
  material_code text not null,
  material_description text,
  item text,
  storage_location text not null default '',
  movement_type text,
  special_stock text,
  material_document text,
  material_doc_item text,
  posting_date date,
  quantity numeric not null default 0,
  unit_of_entry text,
  purchase_order text,
  user_name text,
  invoice_number text,
  vendor text,
  document_header_text text,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  imported_at timestamptz not null default now()
);

alter table public.sap_material_documents enable row level security;

drop policy if exists tenant_isolation on public.sap_material_documents;

create policy tenant_isolation on public.sap_material_documents
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Re-uploading the same MB51 file updates the same document line instead
-- of duplicating it.
create unique index if not exists sap_material_documents_user_doc_item_idx
  on public.sap_material_documents (user_id, material_document, material_doc_item);

create index if not exists sap_material_documents_user_material_date_idx
  on public.sap_material_documents (user_id, material_code, posting_date desc);

create index if not exists sap_material_documents_user_date_idx
  on public.sap_material_documents (user_id, posting_date desc);

-- ---------------------------------------------------------------------------
-- 2. sap_stock_distribution - MB52 snapshot (current qty per material+SLoc)
-- ---------------------------------------------------------------------------
create table if not exists public.sap_stock_distribution (
  id bigint generated by default as identity primary key,
  material_code text not null,
  storage_location text not null,
  quantity numeric not null default 0,
  source_file text,
  imported_at timestamptz not null default now(),
  user_id uuid references auth.users(id) on delete cascade default auth.uid()
);

alter table public.sap_stock_distribution enable row level security;

drop policy if exists tenant_isolation on public.sap_stock_distribution;

create policy tenant_isolation on public.sap_stock_distribution
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create unique index if not exists sap_stock_distribution_user_material_sloc_idx
  on public.sap_stock_distribution (user_id, material_code, storage_location);

-- ---------------------------------------------------------------------------
-- 3. stock_reconciliation_reviews - SAP total vs app total differences
-- ---------------------------------------------------------------------------
create table if not exists public.stock_reconciliation_reviews (
  id bigint generated by default as identity primary key,
  material_code text not null,
  short_description text,
  uom text,
  sap_total numeric not null,
  app_total numeric not null,
  difference numeric not null,
  sloc_breakdown jsonb not null default '[]'::jsonb,
  status text not null default 'open' check (status in ('open', 'applied', 'dismissed')),
  source_file text,
  applied_at timestamptz,
  applied_remarks text,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  created_at timestamptz not null default now()
);

alter table public.stock_reconciliation_reviews enable row level security;

drop policy if exists tenant_isolation on public.stock_reconciliation_reviews;

create policy tenant_isolation on public.stock_reconciliation_reviews
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- At most one open review per material: a fresh MB52 import replaces it.
create unique index if not exists stock_reconciliation_reviews_user_material_open
  on public.stock_reconciliation_reviews (user_id, material_code)
  where status = 'open';

create index if not exists stock_reconciliation_reviews_user_status_idx
  on public.stock_reconciliation_reviews (user_id, status, created_at desc);

-- ---------------------------------------------------------------------------
-- 4. sap_imports - provenance of which material documents were imported
-- ---------------------------------------------------------------------------
create table if not exists public.sap_imports (
  id bigint generated by default as identity primary key,
  material_document text not null,
  file_name text,
  row_count int not null default 0,
  imported_at timestamptz not null default now(),
  user_id uuid references auth.users(id) on delete cascade default auth.uid()
);

alter table public.sap_imports enable row level security;

drop policy if exists tenant_isolation on public.sap_imports;

create policy tenant_isolation on public.sap_imports
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create unique index if not exists sap_imports_user_document_idx
  on public.sap_imports (user_id, material_document);

commit;
